name: editoconfig

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest



        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   uses: zbeekman/EditorConfig-Action@v1.1.0
